@startuml CdU_Sistema
left to right direction

actor "Sistema Generador de Exámenes" as Sistema

usecase "Conectarse a la Base de Datos Universitaria" as ConectarBD
usecase "Recopilar Datos de Asignaturas, Profesores, Aulas y Alumnos" as RecopilarDatos
usecase "Asignar Fechas y Horarios Automáticamente" as AsignarFechas
usecase "Verificar Conflictos de Exámenes" as VerificarConflictosSistema
usecase "Generar Calendario Final" as GenerarCalendarioFinal
usecase "Emitir Advertencias de Conflictos" as EmitirAdvertencias
usecase "Publicar Calendario" as PublicarCalendario

Sistema --> ConectarBD
Sistema --> RecopilarDatos
Sistema --> AsignarFechas
Sistema --> VerificarConflictosSistema
Sistema --> EmitirAdvertencias
Sistema --> GenerarCalendarioFinal
Sistema --> PublicarCalendario

@enduml
