@startuml
title diagramaDeObjetosCorregido

object Universidad {
  nombre = "Uneatlantico"
}

object Facultad {
  nombre = "Politecnica superior"
}

object Grado {
  nombre = "3º grado"
}

object Asignatura {
  nombre = "Ingeniería de Software"
  codigo = "IDSW1"
}

object Examen{
    asignatura = "Ingeniería de Software"
  tipo = "Final"
  fecha = "2025-06-10"
}


object Profesor {
  nombre = "Manuel Masías"
}

object FranjaHoraria{
  descripcion = "08:30 - 10:30"
}


object Aula {
  codigo = "Aula -2.6"
  capacidad = 50
}


object Alumno {
    cantidadAlumno = 50
}


Universidad -- Facultad : tiene >
Facultad -- Grado : tiene >
Grado-- Asignatura : tiene >

Asignatura -- Examen: tiene >

Asignatura -- Profesor : impartida por >
Asignatura -- Alumno : tiene matriculados >

Examen -- FranjaHoraria : tiene >
Examen -- Aula : se realiza en >
Examen -- Profesor : supervisado por >
Examen -- Alumno : realizado por >


@enduml
