@startuml

Class Examen{
  fecha;
  hora;
  convocatoria;
}

Class Grado{
  nombre
}

Class Aula{
  codigo;
  capacidad;
}

Class CursoAcademico{
  numero
}

Class Asignatura{
  nombre
}

Class Turno{
  horainicio
}

CalendarioExamen -- Examen: tiene 
CalendarioExamen -- Grado: incluye
CalendarioExamen -- Admin: gestionada/publicada_por
Examen -- Aula: utiliza >
Examen -- Alumno: hace
Examen -- Asignatura: pertenece_a >
Examen -- Vigilante: vigila 
Grado -- CursoAcademico: pertenece_a
CursoAcademico -- Turno: tiene 
CursoAcademico -- Asignatura: tiene 


@enduml
