@startuml
title Diagrama de Clases - Sistema de Asignación de Exámenes

class Universidad {
    
}

class Facultad {
    
}

class Grado {
   
}

class Materia {
   
}

class Profesor {
    
    
}

class Alumno {
  
}

class Examen {
    

}

class Aula {
   
}

class PlanificadorExamenes {
  
}

Universidad "1" -- "cuenta" Facultad
Facultad "1" -- "tiene" Grado
Grado "1" -- "tiene" Materia
Grado "1" -- "many" Alumno
Materia "1" -- "presentan" Examen
Profesor "1" -- "imparten" Materia
Examen "many" -- "presentan" Alumno
Examen "1" --> "1" Aula
PlanificadorExamenes ..> Examen : gestiona >
PlanificadorExamenes ..> Alumno : valida >
PlanificadorExamenes ..> Materia : planifica >

@enduml
