@startuml CdU_Profesor
left to right direction

actor Profesor

package "Consultas de Exámenes" {
    usecase "Consultar Fechas de Exámenes" as ConsultarFechas
    usecase "Consultar Aula Asignada" as ConsultarAula
    usecase "Verificar Conflictos de Horario" as VerificarConflictosProfesor
}

Profesor --> ConsultarFechas
Profesor --> ConsultarAula
Profesor --> VerificarConflictosProfesor

@enduml
