@startuml CdU_Usuario
left to right direction

actor Usuario

usecase "Iniciar Sesión" as IniciarSesion
usecase "Generar Calendario de Exámenes" as GenerarCalendario
usecase "Verificar Conflictos de Exámenes" as VerificarConflictos
usecase "Consultar Calendario Generado" as ConsultarCalendario
usecase "Exportar o Publicar Calendario" as ExportarCalendario
usecase "Cerrar Sesión" as CerrarSesion

package "Gestión de Datos Universitarios" {
    usecase "Obtener Datos de la Base de Datos" as ObtenerDatos
    usecase "Actualizar Información de Asignaturas" as ActualizarAsignaturas
    usecase "Actualizar Información de Profesores" as ActualizarProfesores
    usecase "Actualizar Información de Aulas" as ActualizarAulas
}

Usuario --> IniciarSesion
Usuario --> ObtenerDatos
Usuario --> ActualizarAsignaturas
Usuario --> ActualizarProfesores
Usuario --> ActualizarAulas
Usuario --> GenerarCalendario
Usuario --> VerificarConflictos
Usuario --> ConsultarCalendario
Usuario --> ExportarCalendario
Usuario --> CerrarSesion

@enduml
