@startuml

object universidad1 {
  nombre = "Universidad Europea del Atlántico"
}

object baseDeDatos {
  nombre = "DB_Universidad"
}

object sistema {
  nombre = "GeneradorAutomáticoExamenes"
}

object calendario

object examen1 {
  fecha = "13 enero"
  hora = "8:30"
}

object asignatura1 {
  nombre = "Ingeniería de Software I"
  codigo = "INF123"
  tipo = "Obligatoria"
  grado = "Ingeniería Informática"
  año = "3.º"
  semestre = "1ro"
}

object profesor1 {
  nombre = "Manuel Masias"
}

object aula1 {
  nombre = "Aula 1.1"
}

object alumno1 {
  nombre = "Alejandro Juárez"
}

universidad1 --> baseDeDatos
sistema --> baseDeDatos
sistema --> calendario
calendario --> examen1
examen1 --> asignatura1
examen1 --> profesor1
examen1 --> aula1
examen1 --> alumno1
@enduml
