@startuml

class Universidad
class BaseDeDatos
class SistemaGeneradorExamenes
class Examen
class Asignatura
class Profesor
class Alumno
class Aula
class CalendarioExamenes
class GeneradorFechas
class VerificadorConflictos
class Usuario

Universidad --> BaseDeDatos : tiene
BaseDeDatos --> Asignatura : tiene
BaseDeDatos --> Profesor : tiene
BaseDeDatos --> Alumno : tiene
BaseDeDatos --> Aula : tiene

SistemaGeneradorExamenes --> BaseDeDatos : tiene
SistemaGeneradorExamenes --> CalendarioExamenes : tiene
SistemaGeneradorExamenes --> GeneradorFechas : tiene
SistemaGeneradorExamenes --> VerificadorConflictos : tiene

CalendarioExamenes --> Examen : tiene
Examen --> Asignatura : tiene
Examen --> Profesor : tiene
Examen --> Aula : tiene
Examen --> Alumno : tiene

Usuario --> SistemaGeneradorExamenes : tiene

@enduml
