@startuml

class Universidad
class Facultad
class Grado
class Asignatura
class Profesor
class Alumno
class Aula
class Examen
class FranjaHoraria

Universidad *-- Facultad : tiene
Facultad *-- Grado : tiene
Grado *-- Asignatura : tiene

Asignatura *--* Profesor : tiene
Asignatura *-- Alumno : tiene matriculados

Asignatura *-- Examen : tiene

Examen --> Aula : se realiza en
Examen --> Profesor : supervisado por
Examen --> FranjaHoraria : tiene
Examen *--* Alumno : realizado por


hide empty members
@enduml
